### PR TITLE
Fix example in README.md

### PR DESCRIPTION
**Pull request by toge**
It's a minor issue.
But for newcomers, this may solve the problem.

### CODE REVIEW

**Comment by guycipher** [comment]
I get that for sure.  One thing though I know this is pretty tedious but for consistency.  
```c
tidesdb_t *tdb;
```

The asterisk at the start of the name.

**Comment by guycipher** [comment]
I know its tedious stuff but when you read the code right from top to bottom get a feel on consistency across the board.

**Comment by guycipher** [comment]
I'm at work so I won't be able to make that change but yeah.  If you want to commit a new readme or new pr thats fine or I'll do it when I get back as I have to finish a other stuff on the engine too :)

**Comment by toge** [comment]
@guycipher 
Oh. It's due to my coding rule!
I totally agree with the consistency of coding rule.
I updated this PR.

**Comment by guycipher** [comment]
Perfect, thank you!

**Pull request merged**
