### PR TITLE
fix GH action for building tidesdb

### PR DESCRIPTION
**Pull request by evgenykor**

### CODE REVIEW

**Comment by evgenykor** [comment]
Ok now it is correctly building and tests running @guycipher 
https://github.com/tidesdb/tidesdb/actions/runs/12546201054/job/34981637291?pr=247

**Comment by evgenykor** [comment]
Some tests are failing there btw @guycipher  so happy coding :)

**Comment by guycipher** [comment]
Haha!  I see that.  I wonder why on CI and not on my computer!

Investigations in order!  Good work @evgenykor , keep it up!

**Comment by guycipher** [comment]
@evgenykor very cool stuff.  Yeah the code probably minor.   Again kinda odd it runs on my system I have Ubuntu as well.  I will debug and fix!

**Comment by guycipher** [comment]
@evgenykor 
Screenshot from 2024-12-30 08-49-55

Where is `uses: actions/checkout@v4` can we do `actions/checkout@latest`?  I'm not sure why those tests are failing I'm unsure its using latest repo version.

**Comment by guycipher** [comment]
Doing some research maybe something like this?
```
name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout tidesdb repo
      uses: actions/checkout@v4

    - name: Fetch latest changes
      run: git fetch --all

    - name: Install libzstd-dev,liblz4-dev and libsnappy-dev
      run: |
        sudo apt update
        sudo apt install -y libzstd-dev liblz4-dev libsnappy-dev

    - name: configure cmake build for tidesdb
      run: cmake --debug-output  -S . -B build && make -C build/

    - name: run tests
      run: |
        export ASAN_OPTIONS=verify_asan_link_order=0
        cd build
        ctest --output-on-failure
        
```

So we get the latest code?  I don't think it's currently getting latest code.

**Comment by guycipher** [comment]
Ah understood.  Thank you @evgenykor

**Comment by guycipher** [comment]
Hey @evgenykor I am gonna rename the ci to TidesDB CI instead of C/C++ CI as that sounds too generic.  

One more piece `export ASAN_OPTIONS=verify_asan_link_order=0` I don't think this is required.  The CMake has all this included for unix systems.
Screenshot from 2024-12-30 13-08-13
This could surely cause undefined behavior.

**Pull request merged**
